import { Component, OnInit } from '@angular/core';
import { CommonModule, DatePipe } from '@angular/common'; // Import DatePipe
import { RouterModule } from '@angular/router';
import { SellerOrderService, SellerOrder } from '../../Services/seller/seller-order.service';
import { Observable, of, EMPTY } from 'rxjs';
import { catchError } from 'rxjs/operators';
import { SellerProductService, SellerOrderItemDTO } from '../seller-products/seller-product.service'; // Use updated service

@Component({
    selector: 'app-seller-order-list',
    standalone: true,
    imports: [
        CommonModule,
        RouterModule,
        // No need to explicitly import DatePipe here if using standalone component providers
        // If using modules, DatePipe would need to be in imports or providers
    ],
    providers: [DatePipe], // Provide DatePipe for standalone component
    templateUrl: './seller-order-list.component.html',
    styleUrls: ['./seller-order-list.component.css']
})
export class SellerOrderListComponent implements OnInit {

    sellerOrders$: Observable<SellerOrder[]> = of([]);
    isLoading = true;
    errorMessage: string | null = null;
    orderItems$: Observable<SellerOrderItemDTO[]> | undefined;

    constructor(private sellerOrderService: SellerOrderService, private sellerProductService: SellerProductService) { }

    ngOnInit(): void {
        this.loadOrders();
        this.loadOrderItems();
    }

    loadOrders(): void {
        this.isLoading = true;
        this.errorMessage = null;
        this.sellerOrders$ = this.sellerOrderService.getSellerOrders().pipe(
            catchError(err => {
                console.error('Error loading seller orders:', err);
                this.errorMessage = 'حدث خطأ أثناء جلب الطلبات. يرجى المحاولة مرة أخرى.';
                this.isLoading = false;
                return of([]); // Return empty array on error
            })
        );

        // Basic loading indicator handling
        this.sellerOrders$.subscribe(() => this.isLoading = false);
    }

    loadOrderItems(): void {
        this.errorMessage = null;
        this.orderItems$ = this.sellerProductService.getMyOrderItems().pipe(
            catchError(err => {
                console.error('Error loading seller order items:', err);
                this.errorMessage = err.message || 'Failed to load order items.';
                return EMPTY;
            })
        );
    }

    // Potential future method to view order details
    viewOrderDetails(orderId: string | number): void {
        console.log(`Navigate to details for order: ${orderId}`);
        // this.router.navigate(['/seller/orders', orderId]); // Requires Router injection and detail component
    }

    // Method to get a CSS class based on order status for styling
    getStatusClass(status: string): string {
        switch (status?.toLowerCase()) {
            case 'pending': return 'status-pending';
            case 'processing': return 'status-processing';
            case 'shipped': return 'status-shipped';
            case 'delivered': return 'status-delivered';
            case 'cancelled': return 'status-cancelled';
            default: return '';
        }
    }

    // Helper function to translate status
    getStatusTranslation(status: string): string {
        switch (status?.toLowerCase()) {
            case 'pending': return 'قيد الانتظار';
            case 'processing': return 'قيد المعالجة';
            case 'shipped': return 'تم الشحن';
            case 'delivered': return 'تم التوصيل';
            case 'cancelled': return 'ملغي';
            default: return status || 'غير معروف'; // Return original or Unknown
        }
    }

    // Optional: Add methods for seller actions (e.g., mark as shipped)
    updateStatus(orderId: number, newStatus: string): void {
        this.errorMessage = null;
        const actionText = newStatus === 'Cancelled' ? 'إلغاء' : 'تحديث حالة';
        if (confirm(`هل أنت متأكد من رغبتك في ${actionText} الطلب رقم ${orderId} إلى '${this.getStatusTranslation(newStatus)}'؟`)) {
            this.sellerProductService.updateOrderStatus(orderId, newStatus).subscribe({
                next: (response) => {
                    console.log(`Order ${orderId} status updated to ${newStatus}`, response);
                    alert(`تم ${actionText} الطلب بنجاح.`);
                    // Refresh the list to show the updated status
                    this.loadOrderItems();
                },
                error: (err) => {
                    // Log the full error object for detailed inspection
                    console.error(`Error updating order ${orderId} status (Full Error Object):`, err);
                    // Use the message generated by the improved handleError
                    this.errorMessage = err.message || `فشل ${actionText} الطلب.`;
                }
            });
        }
    }
} 